### ISSUE TITLE
Bull Board UI stuck on "Loading" 

### ISSUE THREAD

**Issue by whydnxx** [felixmosh/bull-board#378]
Hi, we have been looking for something to monitor our Bull Queues for quite some time. and I use Bull Board for monitor queues,
I'm using Fastift rather than Express, and I have been stuck on Loading... This happened only on production, but on development all going well.

![image](https://user-images.githubusercontent.com/50127599/153448305-82deedba-4deb-43a4-a894-861c8301030a.png)
![image](https://user-images.githubusercontent.com/50127599/153448342-b15a4a83-3c4a-41f2-98ad-d9a26ae1c34d.png)

Reproduce:
```ts
export const setupBullBoard = (app: NestFastifyApplication) => {
  const bullServerAdapter = new BullFastifyAdapter();
  bullServerAdapter.setBasePath('/queues/ui');

  const queues = Object.values(QUEUES).map(
    (queue) => new BullAdapter(new Queue(queue)),
  );

  createBullBoard({
    queues,
    serverAdapter: bullServerAdapter,
  });

  app.register(bullServerAdapter.registerPlugin(), {
    prefix: '/queues/ui',
    basePath: '',
  });
};
```

"bull": "^4.2.1"
"@nestjs/core": "^8.2.5"
"@bull-board/fastify": "^3.9.0"

**Comment by felixmosh** [comment]
I'm not able to reproduce.
I've used the [with-fastify](https://github.com/felixmosh/bull-board/tree/master/examples/with-fastify) example, and change to you prefixes.
All works.

If it works on dev but not on prod, it is probably a problem of mounting point, can you share the prefix that you have on prod?

**Comment by felixmosh** [comment]
Pay attention that you get 504, gateway time out, it is for sure related to your prod setup

**Comment by whydnxx** [comment]
yes, on my production server always loading, is my prefix that must use versioning (v1)? but, in development server is going well

**Comment by felixmosh** [comment]
can you share you url path (without the domain) of the bull ui & the API requests it made?

**Comment by whydnxx** [comment]
endpoint for bull UI is : URL/queues/ui
but I don't understand what API Request you mean
did you mean this?
swagger: /v1/docs/static/index.html
bull ui: /queues/ui
sample: v1/public/...

**Comment by felixmosh** [comment]
can you open the console, and check where the UI makes it's api requests?

**Comment by felixmosh** [comment]
So routes look OK.
you have probably an issue with reverse-proxy on your prod env.
Do you have one? (a reverse proxy)

**Comment by whydnxx** [comment]
No I don't have, and I try to direct using IP and port, it same

**Comment by felixmosh** [comment]
It. Is not related to IP.

You don't have nginx or something similar?

**Comment by whydnxx** [comment]
finally, I found the thing that makes why it always loads, on my dev, running locally without docker. then I tried to run in my dev workspace using docker. the result is the same as in production, I use Docker in production.

Heres is my docker setup: 
```
version: '2'
services:
  app:
    build: .
    container_name: app-api
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
      - .env:/app/.env
    ports:
      - 8080:8080

  db:
    image: postgres:12
    container_name: app-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: just_pay
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql

  redis:
    image: redis:5
    container_name: app-redis
    restart: always
    ports:
      - 6379:6379

volumes:
  postgresdata:

```
