### ISSUE TITLE
[docker][fastify] Queues show no jobs at all

### ISSUE THREAD

**Issue by tniercke-tbs** [felixmosh/bull-board#612]
Hi folks,

I have a already running REDIS instance that uses Bull to manage queues.
To monitor those queues I have set up a docker container with Bull-Board and startet the index.js shown below.
The connection to REDIS can be established, the queues are read correctly and addeed to bullboard.
But no jobs are shown for any queue in any state.
With the tool "RedisInsight" I can see all the queues and their jobs.
The pattern is: `bull:myqueue:repeat:cryptical_job_hash:timestamp:keys`

Do I miss something? 
Is it just not working with docker or is it a bug ?

Any hints are welcome :-)

This is my index.js:
```
const { createBullBoard } = require('@bull-board/api');
const { FastifyAdapter } = require('@bull-board/fastify');
const { BullAdapter } = require('@bull-board/api/bullAdapter')
const Queue = require('bull');
const fastify = require('fastify');
const Redis = require('ioredis');

const run = async () => {
  const {
    DASHBOARD_ROOT_PATH = '/',
    REDIS_HOST = 'redis',
    REDIS_PORT = 6379,
    REDIS_DB_NAME = '0',
    REDIS_DB_PASS = '',
    EXPOSE_PORT = 3000,
    QUEUE_FILTER = ''
  } = process.env;

  const redis = new Redis({
    port: REDIS_PORT,
    host: REDIS_HOST,
    db: REDIS_DB_NAME,
    password: REDIS_DB_PASS,
  });

  // get queues
  const keys = await redis.keys(QUEUE_FILTER + '*');
  const queueNamesSet = new Set(keys.map(key => key.replace(/^.+?:(.+?):.+?$/, '$1')));
  const queues = Array.from(queueNamesSet).map(
    (item) => new BullAdapter(
      new Queue(item, { redis: { port: REDIS_PORT, host: REDIS_HOST, db: REDIS_DB_NAME, password: REDIS_DB_PASS}, }),
      { readOnlyMode: true }
    )
  );

  // create app
  const app = fastify({ logger: true });

  const serverAdapter = new FastifyAdapter();

 const { addQueue, removeQueue, setQueues, replaceQueues } = createBullBoard({
    queues: queues,
    serverAdapter: serverAdapter,
  });

  serverAdapter.setBasePath(DASHBOARD_ROOT_PATH);
  app.register(serverAdapter.registerPlugin(), { prefix: DASHBOARD_ROOT_PATH });
  await app.listen(EXPOSE_PORT, '0.0.0.0');
  console.log(`Running on http://0.0.0.0:` + EXPOSE_PORT + `${DASHBOARD_ROOT_PATH}...`);
};

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
```

And this is my (anonymized) docker-compose file:

```
version: "3.7"

services:

  bullboard:
    image: xjrcode/bull-board:latest
    container_name: bull-board
    environment:
      REDIS_HOST: <REDACTED>
      REDIS_PORT: <REDACTED>
      REDIS_DB_NAME: 0
      REDIS_DB_PASS: <REDACTED>
      EXPOSE_PORT: 8444
      QUEUE_FILTER: ''
      DASHBOARD_ROOT_PATH: /ui

    ports:
      - <REDACTED>:8444:8444

    volumes:
      - ./bullboard-app/index.js:/app/index.js
```
